# remap prefix from 'C-b' to 'C-l'
unbind C-b
set-option -g prefix C-l
bind-key C-l send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Ensure window index numbers get reordered on delete.
set-option -g renumber-windows on

# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# DESIGN TWEAKS

set -g status-style bg='#3c3836'

left_separator_main="\uE0B0"
right_separator_sub="\uE0B3"

set -g status-left '#[bg=#a89984,fg=#222222,bold] #H #[bg=default,fg=#a89984]#{left_separator_main} #S'
set -g status-right ' %H:%M '

set -g status-justify centre
setw -g window-status-format '#[fg=#c5b797] #I:#W '
setw -g window-status-current-format '#[fg=#c5b797,bold] #I:#W '
 
# Pane border colors
set -g pane-border-style 'fg=#30363d'
set -g pane-active-border-style 'fg=#00e68a'

set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',xterm-256color:Tc'
